package com.verix.landing.domain.model;

import java.util.HashMap;
import java.util.Map;

public class LandingStub {
    public static final String EMPTY_STRING = "";
    public static final String INVALID_CHARS = "!¡'¿+ç´%*";
    public static final String NULL = null;

    //Valid cases
    public static Landing allFields() {
        return new Landing(
                "10036/45578",
                "B8RW",
                "Intranet Portal - SBP",
                "Microsoft",
                "Operating System",
                "Windows Server",
                "45578",
                "Windows Server 2016 Standard 10.0.14393.5502",
                ">36 Months",
                "Francisco Aristeguieta Silva",
                "Peru",
                "Tier 2",
                "Yes",
                "No",
                "Draft",
                "38860",
                "DES-WS2016-PG",
                "11/01/2025",
                "10/31/2026",
                "Yes",
                "WS2016",
                "En revisión.",
                "0",
                "0",
                "0",
                "01/12/2027",
                "01/12/2027",
                "01/12/2027",
                "No",
                "Peru",
                "No",
                "false",
                "Production",
                "Prod,DR,UAT/QAT/Pre-PROD,IST,Dev"
        );
    }

    public static Landing onlyRequiredFields(){
        return new Landing(
            "10036/45578",
                "B8RW",
                "Intranet Portal - SBP",
                "Microsoft",
                "Operating System",
                "Windows Server",
                "45578",
                "Windows Server 2016 Standard 10.0.14393.5502",
                ">36 Months",
                "Francisco Aristeguieta Silva",
                "Peru",
                EMPTY_STRING,
                "Yes",
                "No",
                "Missing",
                EMPTY_STRING,
                EMPTY_STRING,
                EMPTY_STRING,
                EMPTY_STRING,
                EMPTY_STRING,
                EMPTY_STRING,
                EMPTY_STRING,
                EMPTY_STRING,
                EMPTY_STRING,
                EMPTY_STRING,
                EMPTY_STRING,
                EMPTY_STRING,
                EMPTY_STRING,
                "No",
                "Peru",
                "No",
                "false",
                "Production",
                "Prod,DR,UAT/QAT/Pre-PROD,IST,Dev");
    }

    public static Landing invalidCharsForOptional(){
        return new Landing(
                "10036/45578",
                "B8RW",
                "Intranet Portal - SBP",
                "Microsoft" ,
                "Operating System" ,
                "Windows Server" ,
                "45578" ,
                "Windows Server 2016 Standard 10.0.14393.5502" ,
                ">36 Months" ,
                "Francisco Aristeguieta Silva" ,
                "Peru" ,
                INVALID_CHARS ,
                "Yes" ,
                "No" ,
                "Missing" ,
                INVALID_CHARS,
                INVALID_CHARS ,
                INVALID_CHARS,
                INVALID_CHARS ,
                INVALID_CHARS,
                INVALID_CHARS ,
                INVALID_CHARS,
                INVALID_CHARS ,
                INVALID_CHARS,
                INVALID_CHARS ,
                INVALID_CHARS,
                INVALID_CHARS ,
                INVALID_CHARS ,
                "No" ,
                "Peru" ,
                "No" ,
                "false" ,
                "Production" ,
                "Prod,DR,UAT/QAT/Pre-PROD,IST,Dev");

    }

    //Invalid cases
    public static Landing invalidCharsForRequiredFields(){
        return new Landing(
                INVALID_CHARS,
                INVALID_CHARS,
                INVALID_CHARS,
                INVALID_CHARS,
                INVALID_CHARS,
                INVALID_CHARS,
                INVALID_CHARS,
                INVALID_CHARS,
                INVALID_CHARS,
                INVALID_CHARS,
                INVALID_CHARS,
                "Tier 2",
                INVALID_CHARS,
                INVALID_CHARS,
                INVALID_CHARS,
                "38860",
                "DES-WS2016-PG",
                "11/01/2025",
                "10/31/2026",
                "Yes",
                "WS2016",
                "En revisión.",
                "0",
                "0",
                "0",
                "01/12/2027",
                "01/12/2027",
                "01/12/2027",
                INVALID_CHARS,
                INVALID_CHARS,
                INVALID_CHARS,
                INVALID_CHARS,
                INVALID_CHARS,
                INVALID_CHARS);

    }

    public static Landing onlyOptionalFields() {
        return new Landing(
                EMPTY_STRING,
                EMPTY_STRING,
                EMPTY_STRING,
                EMPTY_STRING,
                EMPTY_STRING,
                EMPTY_STRING,
                EMPTY_STRING,
                EMPTY_STRING,
                EMPTY_STRING,
                EMPTY_STRING,
                EMPTY_STRING,
                "Tier 2",
                EMPTY_STRING,
                EMPTY_STRING,
                EMPTY_STRING,
                "38860",
                "DES-WS2016-PG",
                "11/01/2025",
                "10/31/2026",
                "Yes",
                "WS2016",
                "En revisión.",
                "0",
                "0",
                "0",
                "01/12/2027",
                "01/12/2027",
                "01/12/2027",
                EMPTY_STRING,
                EMPTY_STRING,
                EMPTY_STRING,
                EMPTY_STRING,
                EMPTY_STRING,
                EMPTY_STRING);
    }

    public static Landing nullForRequiredFields() {
        return new Landing(
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                "Tier 2",
                NULL,
                NULL,
                NULL,
                "38860",
                "DES-WS2016-PG",
                "11/01/2025",
                "10/31/2026",
                "Yes",
                "WS2016",
                "En revisión.",
                "0",
                "0",
                "0",
                "01/12/2027",
                "01/12/2027",
                "01/12/2027",
                NULL,
                NULL,
                NULL,
                NULL,
                NULL,
                NULL);
    }
}
